import PDFDocument from "pdfkit";
import type { GeneratedPaper } from "../types/assessment.js";

// ── Constants ─────────────────────────────────────────────────────────────────

const MARGIN = 60;
const PAGE_WIDTH = 595.28; // A4 points
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

const DIFFICULTY_LABEL: Record<string, string> = {
  easy: "Easy",
  medium: "Moderate",
  hard: "Hard",
};

const DIFFICULTY_COLOR: Record<string, string> = {
  easy: "#2e7d32",   // green
  medium: "#e65100", // orange
  hard: "#b71c1c",   // red
};

// ── Main export ───────────────────────────────────────────────────────────────

export function generatePaperPdf(paper: GeneratedPaper): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: MARGIN,
      size: "A4",
      bufferPages: true, // keep all pages in memory so we can add footers at the end
      info: {
        Title: paper.title,
        Subject: paper.subject ?? "Assessment",
        Creator: "VedaAI Assessment Creator",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    renderPaper(doc, paper);

    // ── Add footer to every page ─────────────────────────────────────────────
    // With bufferPages:true, switchToPage() is 0-indexed and safe to call
    // before doc.end().
    const totalPages = doc.bufferedPageRange().count;
    for (let i = 0; i < totalPages; i++) {
      doc.switchToPage(i);
      doc
        .fontSize(8)
        .font("Helvetica")
        .fillColor("#aaaaaa")
        .text(
          `Generated by VedaAI  •  ${paper.title}  •  Page ${i + 1} of ${totalPages}`,
          MARGIN,
          doc.page.height - MARGIN / 2,
          { width: CONTENT_WIDTH, align: "center" }
        );
    }

    // Flush all buffered pages to the output stream
    doc.flushPages();
    doc.end();
  });
}

// ── Rendering helpers ─────────────────────────────────────────────────────────

function renderPaper(
  doc: InstanceType<typeof PDFDocument>,
  paper: GeneratedPaper
): void {
  // ── Header ──────────────────────────────────────────────────────────────────
  drawHorizontalRule(doc, 1.5);
  doc.moveDown(0.4);

  doc
    .fontSize(18)
    .font("Helvetica-Bold")
    .fillColor("#1a1a1a")
    .text(paper.title, { align: "center" });

  if (paper.subject) {
    doc.moveDown(0.3);
    doc
      .fontSize(13)
      .font("Helvetica")
      .fillColor("#444444")
      .text(`Subject: ${paper.subject}`, { align: "center" });
  }

  doc.moveDown(0.4);
  drawHorizontalRule(doc, 1.5);
  doc.moveDown(0.6);

  // ── Meta row: time + marks ───────────────────────────────────────────────────
  const duration = paper.durationMinutes ?? 60;
  const metaY = doc.y;

  doc
    .fontSize(11)
    .font("Helvetica-Bold")
    .fillColor("#1a1a1a")
    .text(`Time Allowed: ${duration} minutes`, MARGIN, metaY, {
      width: CONTENT_WIDTH / 2,
      align: "left",
    });

  doc
    .fontSize(11)
    .font("Helvetica-Bold")
    .fillColor("#1a1a1a")
    .text(
      `Maximum Marks: ${paper.totalMarks}`,
      MARGIN + CONTENT_WIDTH / 2,
      metaY,
      { width: CONTENT_WIDTH / 2, align: "right" }
    );

  doc.moveDown(1.2);

  // ── General instructions ─────────────────────────────────────────────────────
  doc
    .fontSize(10)
    .font("Helvetica-Oblique")
    .fillColor("#555555")
    .text(
      "General Instructions: All questions are compulsory unless stated otherwise.",
      { align: "left" }
    );

  doc.moveDown(0.8);
  drawHorizontalRule(doc, 0.5);
  doc.moveDown(0.8);

  // ── Student info ─────────────────────────────────────────────────────────────
  drawStudentInfo(doc);
  doc.moveDown(0.8);
  drawHorizontalRule(doc, 0.5);

  // ── Sections ─────────────────────────────────────────────────────────────────
  for (const section of paper.sections) {
    doc.moveDown(1.2);
    renderSection(doc, section);
  }
}

// ── Student info block ────────────────────────────────────────────────────────

function drawStudentInfo(doc: InstanceType<typeof PDFDocument>): void {
  doc
    .fontSize(11)
    .font("Helvetica-Bold")
    .fillColor("#1a1a1a")
    .text("Student Information");

  doc.moveDown(0.5);

  const fields = [
    { label: "Name", lineWidth: 200 },
    { label: "Roll Number", lineWidth: 150 },
    { label: "Section", lineWidth: 100 },
  ];

  for (const field of fields) {
    const labelText = `${field.label}: `;
    doc.fontSize(11);
    const labelWidth = doc.widthOfString(labelText);
    const lineY = doc.y + 14;

    doc
      .fontSize(11)
      .font("Helvetica")
      .fillColor("#1a1a1a")
      .text(labelText, { continued: true });

    doc
      .moveTo(MARGIN + labelWidth, lineY)
      .lineTo(MARGIN + labelWidth + field.lineWidth, lineY)
      .strokeColor("#555555")
      .lineWidth(0.75)
      .stroke();

    doc.text(""); // end continued text
    doc.moveDown(0.3);
  }
}

// ── Section block ─────────────────────────────────────────────────────────────

function renderSection(
  doc: InstanceType<typeof PDFDocument>,
  section: {
    label: string;
    title: string;
    instruction: string;
    questions: Array<{
      id: string;
      number: number;
      text: string;
      difficulty: string;
      marks: number;
      type: string;
      options?: string[];
    }>;
  }
): void {
  // Section header box
  const headerY = doc.y;
  doc.rect(MARGIN, headerY, CONTENT_WIDTH, 22).fillColor("#f0f0f0").fill();

  doc
    .fontSize(12)
    .font("Helvetica-Bold")
    .fillColor("#1a1a1a")
    .text(`Section ${section.label}`, MARGIN + 8, headerY + 5, {
      width: CONTENT_WIDTH - 16,
    });

  doc.moveDown(0.2);

  // Section title (strip the "Section X — " prefix if present)
  const cleanTitle = section.title.replace(/^Section\s+[A-Z]\s*[—\-–]\s*/i, "");
  if (cleanTitle) {
    doc.fontSize(11).font("Helvetica-Bold").fillColor("#1a1a1a").text(cleanTitle);
    doc.moveDown(0.2);
  }

  doc
    .fontSize(10)
    .font("Helvetica-Oblique")
    .fillColor("#555555")
    .text(section.instruction);

  // Marks-per-question note (only when all questions carry the same marks)
  if (section.questions.length > 0) {
    const marksEach = section.questions[0].marks;
    if (section.questions.every((q) => q.marks === marksEach)) {
      doc
        .fontSize(10)
        .font("Helvetica")
        .fillColor("#555555")
        .text(
          `Each question carries ${marksEach} mark${marksEach !== 1 ? "s" : ""}.`
        );
    }
  }

  doc.moveDown(0.6);

  for (const q of section.questions) {
    renderQuestion(doc, q);
  }
}

// ── Question block ────────────────────────────────────────────────────────────

function renderQuestion(
  doc: InstanceType<typeof PDFDocument>,
  q: {
    number: number;
    text: string;
    difficulty: string;
    marks: number;
    type: string;
    options?: string[];
  }
): void {
  const diffLabel = DIFFICULTY_LABEL[q.difficulty] ?? q.difficulty;
  const diffColor = DIFFICULTY_COLOR[q.difficulty] ?? "#555555";

  // Page break guard — leave 100pt buffer for footer
  if (doc.y > doc.page.height - MARGIN - 100) {
    doc.addPage();
  }

  // Question number + text + marks on one line
  doc
    .fontSize(11)
    .font("Helvetica-Bold")
    .fillColor("#1a1a1a")
    .text(`Q${q.number}. `, MARGIN, doc.y, { continued: true });

  doc
    .font("Helvetica")
    .fillColor("#1a1a1a")
    .text(q.text, { continued: true });

  doc
    .fillColor("#555555")
    .text(`  [${q.marks}M]`, { continued: false });

  // Difficulty tag
  doc.moveDown(0.15);
  doc
    .fontSize(9)
    .font("Helvetica-Oblique")
    .fillColor(diffColor)
    .text(`   Difficulty: ${diffLabel}`, MARGIN + 20);

  // MCQ options — two columns
  if (q.type === "mcq" && q.options && q.options.length > 0) {
    doc.moveDown(0.3);
    const letters = ["(a)", "(b)", "(c)", "(d)"];
    const colW = CONTENT_WIDTH / 2;

    for (let i = 0; i < Math.min(q.options.length, 4); i++) {
      const col = i % 2;
      const x = MARGIN + 24 + col * colW;

      if (col === 0) {
        if (i > 0) doc.moveDown(0.3);
        doc
          .fontSize(10)
          .font("Helvetica")
          .fillColor("#1a1a1a")
          .text(`${letters[i]}  ${q.options[i]}`, x, doc.y, {
            width: colW - 10,
            continued: i + 1 < q.options.length,
          });
      } else {
        // Place second column at same Y as first column of this row
        doc
          .fontSize(10)
          .font("Helvetica")
          .fillColor("#1a1a1a")
          .text(
            `${letters[i]}  ${q.options[i]}`,
            x,
            doc.y - doc.currentLineHeight(true),
            { width: colW - 10 }
          );
      }
    }
  }

  // Answer lines for written responses
  if (q.type === "short_answer" || q.type === "fill_blank") {
    doc.moveDown(0.5);
    drawAnswerLine(doc);
  } else if (q.type === "long_answer") {
    doc.moveDown(0.5);
    for (let i = 0; i < 4; i++) drawAnswerLine(doc);
  } else if (q.type === "true_false") {
    doc.moveDown(0.3);
    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#888888")
      .text("   ○ True      ○ False", MARGIN + 20);
  }

  doc.moveDown(0.7);
}

// ── Utilities ─────────────────────────────────────────────────────────────────

function drawAnswerLine(doc: InstanceType<typeof PDFDocument>): void {
  const lineY = doc.y + 8;
  doc
    .moveTo(MARGIN + 24, lineY)
    .lineTo(MARGIN + CONTENT_WIDTH, lineY)
    .strokeColor("#cccccc")
    .lineWidth(0.5)
    .stroke();
  doc.moveDown(0.9);
}

function drawHorizontalRule(
  doc: InstanceType<typeof PDFDocument>,
  lineWidth = 0.5
): void {
  doc
    .moveTo(MARGIN, doc.y)
    .lineTo(MARGIN + CONTENT_WIDTH, doc.y)
    .strokeColor("#cccccc")
    .lineWidth(lineWidth)
    .stroke();
}
